apiVersion: v1
kind: Service
metadata:
  name: fashion-redis-service
  namespace: fashion-ai
  labels:
    app: fashion-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: fashion-redis

---

apiVersion: v1
kind: Service
metadata:
  name: fashion-api-service
  namespace: fashion-ai
  labels:
    app: fashion-api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: fashion-api

---

apiVersion: v1
kind: Service
metadata:
  name: fashion-ui-service
  namespace: fashion-ai
  labels:
    app: fashion-ui
spec:
  type: ClusterIP
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP
      name: http
  selector:
    app: fashion-ui
