from __future__ import annotations

import base64
import io
import logging
from PIL import Image, ImageDraw, ImageFont

logger = logging.getLogger("watermark")


class WatermarkService:
    """Service to apply a professional transparent text watermark to fashion designs."""

    def __init__(self, text: str = "Generated by AI Fashion Assistant") -> None:
        self.text = text

    def apply_watermark(self, image: Image.Image, opacity: float = 0.5) -> Image.Image:
        """Apply a professional translucent text watermark to a PIL Image.

        Supports both RGB (JPEG) and RGBA (PNG) images, placing a transparent
        watermark in the bottom-right corner.
        """
        orig_mode = image.mode
        # Ensure image is in RGBA mode for alpha composite blending
        if orig_mode != "RGBA":
            image_rgba = image.convert("RGBA")
        else:
            image_rgba = image.copy()

        width, height = image_rgba.size

        # Create a transparent overlay layer of identical dimensions
        overlay = Image.new("RGBA", image_rgba.size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(overlay)

        # Determine font size relative to image height (approx 2.5% of height)
        font_size = max(12, int(height * 0.025))
        try:
            # Try to load a standard system sans-serif font
            font = ImageFont.truetype("arial.ttf", size=font_size)
        except IOError:
            # Fall back to Pillow default if true type is unavailable
            font = ImageFont.load_default()

        # Calculate bounding box dimensions of the watermark text
        bbox = draw.textbbox((0, 0), self.text, font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]

        # Place the text in the bottom-right corner with 15px padding
        padding = 15
        x = width - text_w - padding
        y = height - text_h - padding

        # Fallback to keep coordinates inside bounds if image is too small
        x = max(padding, x)
        y = max(padding, y)

        # Define translucent color fill (alpha values range 0 - 255)
        alpha = int(255 * opacity)
        text_color = (255, 255, 255, alpha)

        # Draw a subtle drop shadow (60% of text opacity) to keep text legible on light backgrounds
        shadow_color = (0, 0, 0, int(alpha * 0.6))
        draw.text((x + 1, y + 1), self.text, font=font, fill=shadow_color)
        draw.text((x, y), self.text, font=font, fill=text_color)

        # Composite overlay layer onto base image
        watermarked = Image.alpha_composite(image_rgba, overlay)

        # Reconvert back to input's original pixel format (e.g. drop alpha for JPEG/RGB)
        if orig_mode != "RGBA":
            return watermarked.convert(orig_mode)
        return watermarked

    def apply_watermark_to_b64(self, img_b64: str, opacity: float = 0.5) -> str:
        """Apply watermark directly to a base64 encoded image string.

        Detects image type format (PNG/JPEG) and returns watermarked base64 string.
        """
        if not img_b64:
            return img_b64

        try:
            # Handle headers if base64 data includes schema prefix
            header = ""
            if "," in img_b64:
                parts = img_b64.split(",")
                header = parts[0] + ","
                img_b64_data = parts[1]
            else:
                img_b64_data = img_b64

            # Decode base64 to PIL Image
            img_bytes = base64.b64decode(img_b64_data)
            img = Image.open(io.BytesIO(img_bytes))
            fmt = img.format or "PNG"

            # Apply watermark
            watermarked_img = self.apply_watermark(img, opacity=opacity)

            # Re-encode back to base64 format
            buffered = io.BytesIO()
            watermarked_img.save(buffered, format=fmt)
            encoded = base64.b64encode(buffered.getvalue()).decode("utf-8")
            return header + encoded
        except Exception as exc:
            logger.error(f"Error applying watermark to base64 image: {str(exc)}")
            return img_b64
