apiVersion: v1
kind: ConfigMap
metadata:
  name: fashion-assistant-config
  namespace: fashion-ai
  labels:
    app: fashion-assistant
    version: "1.0.0"
data:
  REDIS_HOST: "fashion-redis-service"
  REDIS_PORT: "6379"
  ENV: "production"
  APP_NAME: "AI Fashion Assistant"
  APP_VERSION: "1.0.0"
  GLOBAL_MOCK: "True"
  LOG_LEVEL: "INFO"
