apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fashion-assistant-pvc
  namespace: fashion-ai
  labels:
    app: fashion-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
