apiVersion: v1
kind: Service
metadata:
  name: fashion-assistant-ui-service
  labels:
    app: fashion-assistant
spec:
  type: LoadBalancer
  ports:
    - port: 7860
      targetPort: 7860
      protocol: TCP
      name: ui
  selector:
    app: fashion-assistant
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-assistant-api-service
  labels:
    app: fashion-assistant
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: api
  selector:
    app: fashion-assistant
