"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Filter, Download, Star, ExternalLink } from "lucide-react";

const GALLERY_ITEMS = [
  { id: 1, title: "Silk Aurora Gown", style: "Couture", brand: "Gucci LoRA", prompt: "Haute couture silk evening gown with aurora gradient embroidery", cols: 1, rows: 2, color: "from-purple-900 via-indigo-900 to-violet-950", emoji: "👗", rating: 5 },
  { id: 2, title: "Urban Techwear", style: "Techwear", brand: "SDXL Base", prompt: "ACRONYM techwear utility vest, reflective accents, midnight city", cols: 1, rows: 1, color: "from-slate-800 via-gray-900 to-zinc-950", emoji: "🥷", rating: 5 },
  { id: 3, title: "Minimalist Studio", style: "Minimal", brand: "Zara LoRA", prompt: "Ivory tailored blazer, straight-leg trousers, studio photography", cols: 1, rows: 1, color: "from-neutral-700 via-stone-800 to-zinc-900", emoji: "🤍", rating: 4 },
  { id: 4, title: "Streetwear Editorial", style: "Streetwear", brand: "Nike LoRA", prompt: "Oversized graphic hoodie, cargo pants, Air Jordans, urban editorial", cols: 1, rows: 1, color: "from-orange-900 via-red-900 to-rose-950", emoji: "🏀", rating: 5 },
  { id: 5, title: "Capsule Linen Set", style: "Bohemian", brand: "SDXL Base", prompt: "Bohemian linen co-ord, golden hour, flowing silhouette", cols: 1, rows: 1, color: "from-amber-900 via-yellow-900 to-orange-950", emoji: "🌾", rating: 4 },
  { id: 6, title: "Runway Couture", style: "Couture", brand: "Gucci LoRA", prompt: "Dramatic sculptural gown, runway lighting, Alexander McQueen aesthetic", cols: 1, rows: 2, color: "from-rose-900 via-pink-900 to-fuchsia-950", emoji: "💃", rating: 5 },
];

const FILTERS = ["All", "Couture", "Streetwear", "Minimal", "Techwear", "Bohemian"];

export default function GallerySection() {
  const [activeFilter, setActiveFilter] = useState("All");
  const [hoveredId, setHoveredId] = useState<number | null>(null);

  const filtered = activeFilter === "All"
    ? GALLERY_ITEMS
    : GALLERY_ITEMS.filter((i) => i.style === activeFilter);

  return (
    <section id="gallery" className="py-32 relative overflow-hidden scroll-mt-20">
      <div className="absolute inset-0 bg-gradient-to-b from-[hsl(225,25%,6%)] via-[hsl(225,20%,8%)] to-[hsl(225,25%,6%)]" />

      <div className="relative z-10 max-w-7xl mx-auto px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold text-pink-300 border border-pink-500/30 bg-pink-500/10 mb-4">
            GENERATION GALLERY
          </span>
          <h2 className="text-5xl md:text-6xl font-black text-white mb-4">
            Created by <span className="gradient-text">AI Fashion Studio</span>
          </h2>
          <p className="text-xl text-slate-400 max-w-xl mx-auto">
            Real designs generated by the studio using SDXL, ControlNet, and brand LoRA adapters.
          </p>
        </motion.div>

        {/* Filters */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="flex items-center gap-3 mb-10 flex-wrap"
        >
          <Filter className="w-4 h-4 text-slate-500" />
          {FILTERS.map((f) => (
            <button
              key={f}
              onClick={() => setActiveFilter(f)}
              className={`px-4 py-2 rounded-xl text-sm font-medium transition-all duration-200 ${
                activeFilter === f
                  ? "bg-indigo-600 text-white shadow-[0_0_15px_rgba(99,102,241,0.4)]"
                  : "glass border border-white/10 text-slate-400 hover:text-white hover:border-indigo-500/30"
              }`}
            >
              {f}
            </button>
          ))}
        </motion.div>

        {/* Gallery grid */}
        <motion.div layout className="grid grid-cols-2 md:grid-cols-3 gap-6">
          <AnimatePresence>
            {filtered.map((item, i) => (
              <motion.div
                key={item.id}
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ delay: i * 0.05 }}
                className={`relative rounded-2xl overflow-hidden cursor-pointer group ${
                  item.rows === 2 ? "row-span-2" : ""
                }`}
                style={{ aspectRatio: item.rows === 2 ? "1/2" : "1/1" }}
                onHoverStart={() => setHoveredId(item.id)}
                onHoverEnd={() => setHoveredId(null)}
              >
                {/* Image placeholder with gradient */}
                <div className={`absolute inset-0 bg-gradient-to-br ${item.color} transition-transform duration-500 group-hover:scale-105`} />

                {/* Fashion emoji centered */}
                <div className="absolute inset-0 flex items-center justify-center text-6xl opacity-25 group-hover:opacity-35 transition-opacity">
                  {item.emoji}
                </div>

                {/* Hover overlay */}
                <AnimatePresence>
                  {hoveredId === item.id && (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      className="absolute inset-0 bg-black/60 backdrop-blur-sm flex flex-col justify-end p-6"
                    >
                      <div className="flex items-center gap-1 mb-2">
                        {Array.from({ length: item.rating }).map((_, i) => (
                          <Star key={i} className="w-3 h-3 text-amber-400 fill-amber-400" />
                        ))}
                      </div>
                      <h3 className="text-white font-bold text-sm mb-0.5">{item.title}</h3>
                      <p className="text-slate-400 text-xs mb-3 line-clamp-2">{item.prompt}</p>
                      <div className="flex items-center gap-2">
                        <span className="px-2 py-0.5 rounded-full bg-indigo-600/40 text-indigo-300 text-xs border border-indigo-500/30">
                          {item.brand}
                        </span>
                        <span className="px-2 py-0.5 rounded-full bg-white/10 text-slate-300 text-xs">
                          {item.style}
                        </span>
                        <div className="ml-auto flex gap-1">
                          <button className="p-1.5 glass rounded-lg hover:bg-white/10 transition-colors">
                            <Download className="w-3 h-3 text-white" />
                          </button>
                          <button className="p-1.5 glass rounded-lg hover:bg-white/10 transition-colors">
                            <ExternalLink className="w-3 h-3 text-white" />
                          </button>
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>

        {/* CTA */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mt-12"
        >
          <a
            href="http://127.0.0.1:7860"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-3 px-8 py-4 rounded-2xl bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold text-lg hover:from-indigo-500 hover:to-purple-500 transition-all duration-300 hover:scale-105 hover:shadow-[0_0_40px_rgba(99,102,241,0.5)]"
          >
            <ExternalLink className="w-5 h-5" />
            Open Full Gallery in Studio
          </a>
        </motion.div>
      </div>
    </section>
  );
}
